const teams=[
  {name: 'Atlanta Hawks', logo:'atlanta_hawks.gif', colors: ['#E03A3E', '#C1D32F']},
  {name: 'Boston Celtics', logo: 'boston_celtics.gif', colors: ['#007A33', '#BA9653']},
  {name: 'Brooklyn Nets', logo: 'brooklyn_nets.gif', colors: ['#FFFFFF', '#000000']},
  {name: 'Charlotte Hornets', logo: 'charlotte_hornets.gif', colors: ['#1D1160', '#00788C']},
  {name: 'Chicago Bulls', logo: 'chicago_bulls.gif', colors: ['#CE1141', '#000000']},
  {name: 'Cleveland Cavaliers', logo: 'cleveland_cavaliers.gif', colors: ['#860038', '#FDBB30']},
  {name: 'Dallas Mavericks', logo: 'dallas_maverics.gif', colors: ['#00538C', '#B8C4CA']},
  {name: 'Denver Nuggets', logo: 'denver_nuggets.gif', colors: ['#0E2240', '#FEC524']},
  {name: 'Detroit Pistons', logo: 'detroit_pistons.gif', colors: ['#C8102E', '#1D42BA']},
  {name: 'Golden State Warriors', logo: 'golden_state_warriors.gif', colors: ['#1D428A', '#FFC72C']},
  {name: 'Houston Rockets', logo: 'houston_rockets.gif', colors: ['#CE1141', '#000000']},
  {name: 'Indiana Pacers', logo: 'indiana_pacers.gif', colors: ['#002D62', '#FDBB30']},
  {name: 'Los Angeles Clippers', logo: 'los_angeles_clippers.gif', colors: ['#C8102E', '#1D428A']},
  {name: 'Los Angeles Lakers', logo: 'los_angeles_lakers.gif', colors: ['#552583', '#FDB927']},
  {name: 'Memphis Grizzlies', logo: 'memphis_grizzlies.gif', colors: ['#5D76A9', '#12173F']},
  {name: 'Miami Heat', logo: 'miami_heat.gif', colors: ['#98002E', '#F9A01B']},
  {name: 'Milwaukee Bucks', logo: 'milwaukee_bucks.gif', colors: ['#00471B', '#EEE1C6']},
  {name: 'Minnesota Timberwolves', logo: 'minnesota_timberwolves.gif', colors: ['#0C2340', '#236192']},
  {name: 'New Orleans Pelicans', logo: 'new_orleans_pelicans.gif', colors: ['#C8102E', '#85714D']},
  {name: 'New York Knicks', logo: 'new_york_knicks.gif', colors: ['#F58426', '#006BB6']},
  {name: 'Oklahoma City Thunder', logo: 'oklahoma_city_thunder.gif', colors: ['#007AC1', '#EF3B24']},
  {name: 'Orlando Magic', logo: 'orlando_magic.gif', colors: ['#0077C0', '#C4CED4']},
  {name: 'Philadelphia 76ers', logo: 'philadelphia_76ers.gif', colors: ['#006BB6', '#ED174C']},
  {name: 'Phoenix Suns', logo: 'phoenix_suns.gif', colors: ['#1D1160', '#E56020']},
  {name: 'Portland Trail Blazers', logo: 'portland_trail_blazers.gif', colors: ['#E03A3E', '#000000']},
  {name: 'Sacramento Kings', logo: 'sacramento_kings.gif', colors: ['#5A2D81', '#63727A']},
  {name: 'San Antonio Spurs', logo: 'san_antonio_spurs.gif', colors: ['#C4CED4', '#000000']},
  {name: 'Toronto Raptors', logo: 'toronto_raptors.gif', colors: ['#CE1141', '#000000']},
  {name: 'Utah Jazz', logo: 'utah_jazz.gif', colors: ['#002B5C', '#00471B']},
  {name: 'Washington Wizards', logo: 'washington_wizards.gif', colors: ['#002B5C', '#E31837']},
]

export default teams
